### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/ux_language#1]
hi @nvkelso, I was working in this small leaflet plugin to replicate what you were doing to change the default language on Tron2.0... but seams not working or I'm not going to the right places. Can you guide me a little in the wiring of it??

**Comment by nvkelso** [comment]
In the main Tron style we use the DAT gui for this. The key thing is you need to pass the value of the new Leaflet UX element to Tangram, updating `scene.config.global.ux_language`, and then ask Tangram to update via `scene.updateConfig();`.

```
        // use query language, else default to English
        gui.language = query.language || false;
        gui.add(gui, 'language', langs).onChange(function(value) {
            scene.config.global.ux_language = value;
            scene.updateConfig();
            //window.location.search = 'language=' + value;
        });
```

It looks like you're doing that slightly differently in https://github.com/tangrams/language-selector/blob/gh-pages/leaflet-tangram-language-selector.js#L50-L51:

```
        languageSelector.onchange = function(onchange){
            console.log(options)
            console.log('Changing language for', onchange.target.value);
            options.scene.config.global[options.global] = onchange.target.value;
            options.scene.updateConfig();
        }
```

But when I use the Leaflet control it never triggers any of that console logging so I suspect it's failing before it gets there.

**Comment by patriciogonzalezvivo** [comment]
hi! I'm doing the same thing... but leaving the door open for some flexibility. `options.global` holds `ux_language`

**Comment by patriciogonzalezvivo** [comment]
I get this in the console:
![screen shot 2016-10-06 at 9 36 25 am](https://cloud.githubusercontent.com/assets/346914/19154457/943596d8-8ba8-11e6-8b3a-16051d9afe69.png)

**Comment by patriciogonzalezvivo** [comment]
I'm trying by changing values in Shanghai (`#6.920183532996774/31.972/120.149`) in tron/tron but nothing changes... any idea way?

![screen shot 2016-10-06 at 9 39 46 am](https://cloud.githubusercontent.com/assets/346914/19154528/ea1dfdc4-8ba8-11e6-8e84-55bea5440b33.png)

**Comment by patriciogonzalezvivo** [comment]
I see... It was working. But I have to be watching closely to places that have other languages like Shanghai (`#15.087716948680919/31.2141/121.4845`)
